### ISSUE TITLE
[BUG] 404 Not Found because of X-Frappe-Site-Name header

### ISSUE THREAD

**Issue by ayandebnath** [The-Commit-Company/frappe-js-sdk#40]
**Describe the bug**
I'm trying to use this library on my React front end but getting 404 Not Found as the backend is on a different origin.

My backend URL is `http://test.localhost:8000` (frappe_docker) and my frontend URL is `http://localhost:5173` (a react project).

This is happening because the value of the `X-Frappe-Site-Name` header is set to `localhost` and I can't change it.

On Postman, when I change the `X-Frappe-Site-Name` header value to `test.localhost` or remove the header, it works.
Also, when I use a simple fetch request without adding the same header, it works.

Is there any way I can change the `X-Frappe-Site-Name` header value manually?

**To Reproduce**
 - Frontend and backend should be hosted separately
 
**Expected behavior**
All the URL endpoints should be accessible from the frontend.

**Screenshots**
![Screenshot_20230823_131039](https://github.com/The-Commit-Company/frappe-js-sdk/assets/48253317/71631c6e-94df-4d18-ac9d-097b98ad2b3a)

![Screenshot_20230823_131201](https://github.com/The-Commit-Company/frappe-js-sdk/assets/48253317/7da85a07-3fd1-4beb-881d-e01c2ca1140f)

**Environment (please complete the following information):**
 - OS: Kubuntu 23.04 with docker
 - Browser: Chrome
 - Frappe: 14.42.0
 
**Additional context**
- Please let me know if I made any mistake.

**Comment by nikkothari22** [comment]
Hey @ayandebnath -

Did you set up your React app using Doppio? If yes, then it automatically adds a proxy server in your local dev environment. 

If not, are you using Vite for your React app?

On a side note, if you are using React, I would recommend you to use frappe-react-sdk.

**Comment by ayandebnath** [comment]
React with vite.

Actually I'm using the `frappe-react-sdk`. As it uses `frappe-js-sdk` under the hood and the issue is related to the `frappe-js-sdk`. That is the reason why I've opened the issue here.

**Comment by nikkothari22** [comment]
If you're using Vite, on your local environment, you should set up a proxy in Vite.config.js so that requests in your React app get proxied to the Frappe server.

You can see Raven's Vite configuration here: https://github.com/The-Commit-Company/Raven/blob/develop/raven-app/vite.config.ts

https://github.com/The-Commit-Company/Raven/blob/develop/raven-app/proxyOptions.js

Will your React app eventually be hosted on the same domain as your Frappe app? (Not talking about Dev, but prod). Frappe uses cookie based auth and you'll run into issues if your Frappe app and React app are on different domains unless you're using OAuth/Token based Authentication. 

We can add the ability to explicitly set the header value in the library, but you shouldn't need it.

**Comment by ayandebnath** [comment]
Setting up the proxy worked. But I still had to change the header value in the proxy otherwise 404.
```
headers: {
    'X-Frappe-Site-Name': 'test.localhost',
},
```


Answering your question:

Yes, we're going to deploy the react app on a separate host. But, if you have any solution to deploy on the same host as the backend then please let me know.

A side note: We want the frontend (react app) root URL to be `/` not anything like `/frontend`.

**Comment by nikkothari22** [comment]
I think you can set up a Frappe redirect to the React home page from the Frappe home page "/". I remember doing this, but I don't remember exactly where - probably in hooks

**Comment by ayandebnath** [comment]
Okay, I'll try and let you know. Thank you.
